# =============================================================================
# backend/app/models/user.py
# ORM model for the `users` table.
# Represents an authenticated user of the DMRE dashboard; the extension may
# operate anonymously (user_id = NULL on memories) or with a linked account.
# =============================================================================

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, generate_uuid


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(
        String(32),
        primary_key=True,
        default=generate_uuid,
        doc="UUID4 hex string, generated by the application layer.",
    )
    username: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        nullable=False,
        index=True,
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
    )
    # Hashed password (bcrypt); nullable to support future OAuth/SSO extension.
    password_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationships — back-populated by child models
    memories: Mapped[list["Memory"]] = relationship(  # noqa: F821
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )
    query_logs: Mapped[list["QueryLog"]] = relationship(  # noqa: F821
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!r} username={self.username!r}>"
