# =============================================================================
# backend/app/services/reranker_service.py
# XGBoost re-ranker service — the original ML contribution of this project.
# Loads the pre-trained reranker_model.pkl and reorders ChromaDB candidates
# using five engineered features to produce the final top-k results shown to
# the user.  The model must NOT be retrained; only inference is performed here.
# =============================================================================

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import numpy as np

# The pkl must sit alongside this file: backend/app/services/reranker_model.pkl
# Generated by running DMRE_Reranker_Training.ipynb (uses joblib.dump).
MODEL_PATH = Path(__file__).parent / "reranker_model.pkl"

_model = None  # lazy singleton


def _get_model():
    """Load reranker_model.pkl on first call; raise a clear error if missing."""
    global _model
    if _model is not None:
        return _model
    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Re-ranker model not found at {MODEL_PATH}.\n"
            "Run the training script: python backend/generate_reranker.py"
        )
    try:
        import joblib  # noqa: PLC0415
    except ImportError as exc:
        raise ImportError("joblib is not installed. Run: pip install scikit-learn") from exc
    _model = joblib.load(MODEL_PATH)
    return _model


# ---------------------------------------------------------------------------
# Feature engineering helpers
# These reproduce the exact feature definitions used during training so that
# the feature matrix fed to the model matches the training distribution.
# ---------------------------------------------------------------------------

def _recency_days(visited_at: datetime) -> float:
    """Days since the page was visited (non-negative float)."""
    now = datetime.now(timezone.utc)
    if visited_at.tzinfo is None:
        visited_at = visited_at.replace(tzinfo=timezone.utc)
    return max(0.0, (now - visited_at).total_seconds() / 86_400.0)


def _engagement_score(visit_count: int, dwell_time: float) -> float:
    """visit_count + dwell_time_minutes — mirrors training feature definition."""
    return float(visit_count) + (dwell_time / 60.0)


def _term_overlap(query: str, title: str) -> float:
    """Jaccard similarity between lowercased query tokens and title tokens."""
    q_tok = set(query.lower().split())
    t_tok = set(title.lower().split())
    if not q_tok or not t_tok:
        return 0.0
    return len(q_tok & t_tok) / len(q_tok | t_tok)


def _time_of_day_match(visited_at: datetime) -> float:
    """1.0 if visited within ±3 hours of the current time-of-day, else 0.0."""
    now_hour = datetime.now(timezone.utc).hour
    visit_hour = visited_at.hour if visited_at.tzinfo else visited_at.replace(tzinfo=timezone.utc).hour
    diff = abs(now_hour - visit_hour)
    diff = min(diff, 24 - diff)  # circular distance across midnight
    return 1.0 if diff <= 3 else 0.0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def rerank(query: str, candidates: list[dict], top_k: int = 5) -> list[dict]:
    """
    Re-rank a list of candidate memories using the pre-trained XGBoost model.

    Feature order (fixed — must match training):
        [semantic_similarity, recency_days, engagement_score,
         term_overlap, time_of_day_match]

    Args:
        query:      Raw query string (used for term_overlap feature).
        candidates: List of dicts, each containing:
                      - semantic_similarity (float, from ChromaDB cosine distance)
                      - visited_at          (datetime)
                      - visit_count         (int)
                      - dwell_time          (float, seconds)
                      - title               (str)
        top_k:      Number of results to return after re-ranking.

    Returns:
        Up to *top_k* candidates sorted by predicted relevance score (descending).
    """
    if not candidates:
        return []

    model = _get_model()

    rows: list[list[float]] = []
    for c in candidates:
        visited_at: datetime = c.get("visited_at") or datetime.now(timezone.utc)
        row = [
            float(c.get("semantic_similarity", 0.0)),
            _recency_days(visited_at),
            _engagement_score(
                int(c.get("visit_count", 1)),
                float(c.get("dwell_time", 0.0)),
            ),
            _term_overlap(query, c.get("title", "")),
            _time_of_day_match(visited_at),
        ]
        rows.append(row)

    X = np.array(rows, dtype=np.float32)
    scores: np.ndarray = model.predict(X)

    paired = sorted(zip(candidates, scores.tolist()), key=lambda x: x[1], reverse=True)
    return [c for c, _ in paired[:top_k]]
